apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-demo
  labels:
    app: devops-pipeline-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-pipeline-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        # zero-downtime deploy
  template:
    metadata:
      labels:
        app: devops-pipeline-demo
    spec:
      containers:
        - name: app
          image: latifaa13/devops-pipeline-demo:IMAGE_TAG
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "IMAGE_TAG"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
